[package]
name = "windows-taskscheduler"
version = "0.3.0"
edition = "2021"

[dependencies.windows]
version = "0.51"
features = [
    "Win32_System_Com",
    "Win32_System_TaskScheduler",
    "Win32_System_Ole",
    "Win32_Foundation",
    "Win32_System_Variant",
]
