[package]
name = "windows-taskscheduler"
version = "0.1.0"
authors = ["scrubjay55"]
edition = "2021"

[workspace]
members = [
    "examples/*",
]

[dependencies.windows]
version = "0.30"
features = ["Win32_System_Com", "Win32_System_TaskScheduler", "Win32_System_Ole", "Win32_Foundation"]